<div class="row">    
    <div class="col-lg-12 margin-10px-0px">
        <div class="row">
            <div class="col-lg-12"><h4 class="text-success">Conheça o Newfinances</h4></div>
            <div class="col-lg-8">
                <img class="img img-rounded pull-left margin-10px" src="<?php echo $this->baseUrl('views/img/system/despesas.png'); ?>" />
                <span class="text-justify">
                    Ipsum Ipsum Ipsum Ipsum Ipsum Ipsum Ipsum Ipsum Ipsum 
                    Ipsum Ipsum Ipsum Ipsum Ipsum Ipsum Ipsum Ipsum Ipsum 
                    Ipsum Ipsum Ipsum Ipsum Ipsum Ipsum Ipsum Ipsum Ipsum 
                    Ipsum Ipsum Ipsum Ipsum Ipsum Ipsum Ipsum Ipsum Ipsum 
                    Ipsum Ipsum Ipsum Ipsum Ipsum Ipsum Ipsum Ipsum Ipsum 
                    Ipsum Ipsum Ipsum Ipsum Ipsum Ipsum Ipsum Ipsum Ipsum 
                    Ipsum Ipsum Ipsum Ipsum Ipsum Ipsum Ipsum Ipsum Ipsum 
                    Ipsum Ipsum Ipsum Ipsum Ipsum Ipsum Ipsum Ipsum Ipsum 
                    Ipsum Ipsum Ipsum Ipsum Ipsum Ipsum Ipsum Ipsum Ipsum 
                    Ipsum Ipsum Ipsum Ipsum Ipsum Ipsum Ipsum Ipsum Ipsum 
                    Ipsum Ipsum Ipsum Ipsum Ipsum Ipsum Ipsum Ipsum Ipsum 
                    Ipsum Ipsum Ipsum Ipsum Ipsum Ipsum Ipsum Ipsum Ipsum 
                    Ipsum Ipsum Ipsum Ipsum Ipsum Ipsum Ipsum Ipsum Ipsum 
                    Ipsum Ipsum Ipsum Ipsum Ipsum Ipsum Ipsum Ipsum Ipsum 
                    Ipsum Ipsum Ipsum Ipsum Ipsum Ipsum Ipsum Ipsum Ipsum 
                    Ipsum Ipsum Ipsum Ipsum Ipsum Ipsum Ipsum Ipsum Ipsum 
                    Ipsum Ipsum Ipsum Ipsum Ipsum Ipsum Ipsum Ipsum Ipsum 
                    Ipsum Ipsum Ipsum Ipsum Ipsum Ipsum Ipsum Ipsum Ipsum 
                    Ipsum Ipsum Ipsum Ipsum Ipsum Ipsum Ipsum Ipsum Ipsum 
                    Ipsum Ipsum Ipsum Ipsum Ipsum Ipsum Ipsum Ipsum Ipsum 
                    Ipsum Ipsum Ipsum Ipsum Ipsum Ipsum Ipsum Ipsum Ipsum 
                    Ipsum Ipsum Ipsum Ipsum Ipsum Ipsum Ipsum Ipsum Ipsum 
                    Ipsum Ipsum Ipsum Ipsum Ipsum Ipsum Ipsum Ipsum Ipsum 
                    Ipsum Ipsum Ipsum Ipsum Ipsum Ipsum Ipsum Ipsum Ipsum 
                    Ipsum Ipsum Ipsum Ipsum Ipsum Ipsum Ipsum Ipsum Ipsum 
                    Ipsum Ipsum Ipsum Ipsum Ipsum Ipsum Ipsum Ipsum Ipsum 
                    Ipsum Ipsum Ipsum Ipsum Ipsum Ipsum Ipsum Ipsum Ipsum                                         
                </span>
            </div>
            <div class="col-lg-4 thumbnail">
                <div class="col-lg-12">
                    <div class="row">
                        <iframe src="//www.facebook.com/plugins/likebox.php?href=https%3A%2F%2Fwww.facebook.com%2Fsisnewfinances&amp;width=370&amp;height=390&amp;colorscheme=light&amp;show_faces=true&amp;header=true&amp;stream=false&amp;show_border=false" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:100%; height:390px;" allowTransparency="true"></iframe>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-lg-12">
        <div class="row">
            <div class="col-lg-12"><h4 class="text-success">Mais sobre o Sistema</h4></div>
            <div class="col-lg-4">
                <div class="thumbnail text-center">
                    <img class="img img-responsive img-circle" src="<?php echo $this->baseUrl('views/img/system/receitas.png'); ?>" alt="">
                    <div class="caption">
                        <h3 class="text-info">Receitas</h3>
                        <p>
                            ipsum ipsum ipsum ipsum ipsum ipsum ipsum ipsum ipsum 
                            ipsum ipsum ipsum ipsum ipsum ipsum ipsum ipsum ipsum 
                            ipsum ipsum ipsum ipsum ipsum ipsum ipsum ipsum ipsum 
                            ipsum ipsum ipsum ipsum ipsum ipsum ipsum ipsum ipsum 
                            ipsum ipsum ipsum ipsum ipsum ipsum ipsum ipsum ipsum 
                        </p>
                        <p><a href="#" class="btn btn-success" role="button">Saiba mais...</a></p>
                    </div>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="thumbnail text-center">
                    <img class="img img-responsive img-circle" src="<?php echo $this->baseUrl('views/img/system/despesas.png'); ?>" alt="">
                    <div class="caption">
                        <h3 class="text-info">Despesas</h3>
                        <p>
                            ipsum ipsum ipsum ipsum ipsum ipsum ipsum ipsum ipsum 
                            ipsum ipsum ipsum ipsum ipsum ipsum ipsum ipsum ipsum 
                            ipsum ipsum ipsum ipsum ipsum ipsum ipsum ipsum ipsum 
                            ipsum ipsum ipsum ipsum ipsum ipsum ipsum ipsum ipsum 
                            ipsum ipsum ipsum ipsum ipsum ipsum ipsum ipsum ipsum 
                        </p>
                        <p><a href="#" class="btn btn-success" role="button">Saiba mais...</a></p>
                    </div>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="thumbnail text-center">
                    <img class="img img-responsive img-circle" src="<?php echo $this->baseUrl('views/img/system/cartoes_credito.png'); ?>" alt="">
                    <div class="caption">
                        <h3 class="text-info">Cartões de Crédito</h3>
                        <p>
                            ipsum ipsum ipsum ipsum ipsum ipsum ipsum ipsum ipsum 
                            ipsum ipsum ipsum ipsum ipsum ipsum ipsum ipsum ipsum 
                            ipsum ipsum ipsum ipsum ipsum ipsum ipsum ipsum ipsum 
                            ipsum ipsum ipsum ipsum ipsum ipsum ipsum ipsum ipsum 
                            ipsum ipsum ipsum ipsum ipsum ipsum ipsum ipsum ipsum 
                        </p>
                        <p>
                            <a href="#" class="btn btn-success" role="button">Saiba mais...</a>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>