<div class="row">    
    <div class="col-lg-12 margin-10px-0px">
        <div class="row">
            <div class="col-lg-12"><h4 class="text-success">Conheça o Newfinances</h4></div>
            <div class="col-lg-8">
                <img class="img img-rounded pull-left margin-10px" src="<?php echo $this->baseUrl('views/img/system/despesas.png'); ?>" />
                <span class="text-justify">
                    <p>
                    O NewFinances é um sistema de controle financeiro no qual 
                    você poderá otimizar suas contas e gerenciar suas finanças 
                    de maneira fácil e objetiva, controlando assim com total 
                    segurança suas receitas e despesas diárias.
                    </p>
                    <p>
                    Hoje em dia é fundamental a necessidade de termos cada vez 
                    mais uma saúde financeira estável, no qual poderemos assim 
                    fazer aqueles investimentos tão sonhados: Aquela viagem 
                    internacional ou comprar o carro novo.
                    </p>
                    <p>
                    O sistema é totalmente voltado para as famílias brasileiras,
                    por isso a necessidade de desenvolvermos algo simples e 
                    prático, simples na forma de usar o sistema e prático no 
                    qual os resultados são facilmente visíveis.
                    </p>
                    <p>
                    Não perca tempo e cadastre-se agora mesmo e desfrute de 
                    todas as vantagens de ser um(a) usuário(a) do NewFinances. 
                    <span class="text-success"><b>Totalmente gratuito.</b></span>                                      
                    </p>
                </span>
            </div>
            <div class="col-lg-4 thumbnail">
                <div class="col-lg-12">
                    <div class="row">
                        <iframe src="//www.facebook.com/plugins/likebox.php?href=https%3A%2F%2Fwww.facebook.com%2Fsisnewfinances&amp;width=370&amp;height=390&amp;colorscheme=light&amp;show_faces=true&amp;header=true&amp;stream=false&amp;show_border=false" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:100%; height:390px;" allowTransparency="true"></iframe>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-lg-12">
        <div class="row">
            <div class="col-lg-12"><h4 class="text-success">Mais sobre o Sistema</h4></div>
            <div class="col-lg-4">
                <div class="thumbnail text-center">
                    <img class="img img-responsive img-circle" src="<?php echo $this->baseUrl('views/img/system/receitas.png'); ?>" alt="">
                    <div class="caption">
                        <h3 class="text-info">Receitas</h3>
                        <p>
                            Cadastre suas receitas inclusive as receitas previstas 
                            e acompanhe a evolução da sua situação financeira.
                        </p>
                        <p><a href="#" class="btn btn-success" role="button">Saiba mais...</a></p>
                    </div>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="thumbnail text-center">
                    <img class="img img-responsive img-circle" src="<?php echo $this->baseUrl('views/img/system/despesas.png'); ?>" alt="">
                    <div class="caption">
                        <h3 class="text-info">Despesas</h3>
                        <p>
                            Cadsatre suas despesas podendo criar orçamentos por 
                            categorias mantendo assim a saúde financeira de sua
                            família.
                        </p>
                        <p><a href="#" class="btn btn-success" role="button">Saiba mais...</a></p>
                    </div>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="thumbnail text-center">
                    <img class="img img-responsive img-circle" src="<?php echo $this->baseUrl('views/img/system/cartoes_credito.png'); ?>" alt="">
                    <div class="caption">
                        <h3 class="text-info">Cartões de Crédito</h3>
                        <p>
                            Controle suas faturas de cartão de crédito, de forma 
                            fácil e prática podendo acompanhar o saldo da fatura. 
                        </p>
                        <p>
                            <a href="#" class="btn btn-success" role="button">Saiba mais...</a>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>