<div class="row">
    <div class="col-lg-12 col-sm-12 text-justify">
        <p><h3 class="text-green">Sobre o Sistema</h3></p>
        <p>
            <span>
                O NewFinances é um sistema de controle financeiro no qual você
            </span>
            <span>
                poderá otimizar suas contas e gerenciar suas finanças de maneira
                fácil e objetiva, controlando assim com total segurança suas 
                receitas e despesas diárias.
            </span>
        </p>
        <p>
            <span>
                Hoje em dia é fundamental a necessidade de termos cada vez mais 
            </span>
            <span>
                uma saúde financeira estável, no qual poderemos assim fazer 
                aqueles investimentos tão sonhados: Aquela viagem internacional 
                ou comprar o carro novo.
            </span>
        </p>
        <p>
            <span>
                O sistema é totalmente voltado para as famílias brasileiras, 
            </span>
            <span>
                por isso a necessidade de desenvolvermos algo simples e prático,
                simples na forma de usar o sistema e prático no qual os 
                resultados são facilmente visíveis.
            </span>
        </p>
        <p>
            <span>
                Não perca tempo e cadastre-se agora mesmo e desfrute de todas 
            </span>
            <span>
                as vantagens de ser um(a) usuário(a) do NewFinances. <b class="text-orange">Totalmente gratuito.</b>
            </span>
        </p>
    </div>
</div>
<hr />
<div class="row">
    <div class="col-sm-4">
        <img class="img-circle img-responsive text-center" src="<?php echo $this->baseUrl('views/img/system/receitas.png'); ?>">
        <h2 class="text-center text-blue">Receitas</h2>
        <p class="text-justify">
            Cadastre suas receitas de forma fácil e objetiva. Podendo 
            cadastrar todas as suas receitas previstas e realizadas.
        </p>
        <div class="navbar-right">
            <a class="background-color-green padding-10px" href="">Leia mais...</a>
        </div>
    </div>
    <div class="col-sm-4">
        <img class="img-circle img-responsive" src="<?php echo $this->baseUrl('views/img/system/despesas.png'); ?>">
        <h2 class="text-center text-blue">Despesas</h2>
        <p class="text-justify">
            Cadastre suas despesas por categorias e fique tranquilo
            de sua saúde financeira.
        </p>
        <div class="navbar-right">
            <a class="background-color-green padding-10px" href="">Leia mais...</a>
        </div>
    </div>
    <div class="col-sm-4">
        <img class="img-circle img-responsive" src="<?php echo $this->baseUrl('views/img/system/cartoes_credito.png'); ?>">
        <h2 class="text-center text-blue">Cartões de Crédito</h2>
        <p class="text-justify">
            Controle seus gastos nos cartões de crédito, podendo
            ver o saldo de sua fatura.
        </p>
        <div class="navbar-right">
            <a class="background-color-green padding-10px" href="">Leia mais...</a>
        </div>
    </div>
</div>
