<div class="col-lg-12">
    <p><h3 class="text-green">Faça Contato</h3></p>
    <?php echo View_Helper_Messages::render($this->messages); ?>
</div>
<div class="col-lg-5">
    <!--<img class="img-banner" src="<?php echo $this->baseUrl('views/img/img_contact_us.jpg'); ?>" />-->
    <p class="margin-top-10px text-justify">
        Por favor, preencha todos os campos ao lado. Em até 2 (dois) dias úteis,
        entraremos em contato.
    </p>
    <p class="text-justify">
        Desde já a equipe <label class="text-blue">NewFinances</label> agradece seu contato.
    </p>
</div>
<div class="col-lg-1">&nbsp;</div>
<div class="col-lg-6 bg">        
    <?php echo $this->formSiteContato; ?>
</div>
