<?php echo $this->headScript()->appendFile($this->baseUrl('views/js/cliente/index/index.js')); ?>
<?php echo $this->headScript()->appendFile($this->baseUrl('views/js/layout.js')); ?>
<div class="row">       
    <div class="col-lg-12">        
        <?php echo View_Helper_Messages::render($this->messages, $this->alerts); ?>
        <div class="panel panel-info">
            <div class="panel-heading">
                <span class="text-info">Lançamentos</span>
                <?php if ($this->isConta) : ?>
                <div class="pull-right">
                    <a href="" data-toggle="modal" data-target="#modalSaldoContas" id="saldo-contas">
                        <img class="margin-0px-5px" src="<?php echo $this->baseUrl('views/img/icon_balance.png'); ?>" width="20" title="Ver Saldo"/>
                        <span class="text-info">Saldo</span>
                    </a>
                    <a href="" data-toggle="modal" data-target="#modalGraficosLancamentos" id="chart-movimentacao">
                        <img class="margin-0px-5px" src="<?php echo $this->baseUrl('views/img/icon_chart.png'); ?>" width="20" title="Visualizar Gráfico"/>
                        <span class="text-info">Gráfico Anual</span>
                    </a>
                </div>
                <?php endif; ?>
            </div>
            <div class="panel-body">
                <div class="panel panel-success">
                    <div class="panel-body">
                        <div class="col-lg-4">    
                            <div class="form-inline pull-left">                        
                                <input class="form-control input-sm" placeholder="Ir para a data" type="text" name="data_movimentacao" id="data_movimentacao"/>
                                <input class="btn btn-success btn-sm" type="submit" name="submit" id="btn_data_movimentacao" value="Ir" />                        
                            </div>    
                        </div>
                        <div class="col-lg-8">
                            <div class="form-inline pull-right">
                                <input class="form-control input-sm" placeholder="Pesquisar" type="text" name="data_movimentacao" id='pesquisar' />
                                <a class="btn btn-xs btn-info" href="<?php echo $this->url(array(
                                    'module' => 'cliente',
                                    'controller' => 'pesquisas',
                                    'action' => 'avancada'
                                ), null, true); ?>">Pesquisa Avançada</a>
                            </div>    
                        </div>                
                    </div>
                </div>                
                <div id="movimentacoes"></div>
            </div>
        </div>    
    </div>
    <div class="col-lg-12">
        <div class="panel panel-info">
            <div class="panel-heading"><span class="text-blue">Faturas</span></div>
            <div class="panel-body">
                <?php if ($this->cartoes->count() > 0) : ?>
                <!-- Nav tabs -->
                <ul class="nav nav-tabs" role="tablist">
                    <li class="active"><a href="#geral" role="tab" data-toggle="tab"><span class="text-info">Geral</span></a></li>           
                    <?php foreach ($this->cartoes as $cartao) : ?>
                    <li>
                        <a href="#<?php echo $cartao->id_cartao; ?>" role="tab" data-toggle="tab">
                            <span class="text-info">                                
                                <?php echo $cartao->descricao_cartao; ?>
                            </span>
                        </a>
                    </li>                                      
                    <?php endforeach; ?>
                </ul>
                
                <!-- Tab panes -->
                <div class="tab-content">
                    <div class="tab-pane fade in active" id="geral">                    
                        <div class="col-lg-12 panel-bordered">
                            faturas gerais
                        </div>                        
                    </div>  
                    <?php foreach ($this->cartoes as $cartao) : ?>
                    <div class="tab-pane fade" id="<?php echo $cartao->id_cartao; ?>">
                        <div class="col-lg-12 panel-bordered">
                            faturas <?php echo $cartao->descricao_cartao; ?>
                        </div>
                    </div>
                    <?php endforeach; ?>                    
                </div>
                <?php else : ?>
                <div class="text-warning">Nenhum cartão de crédito cadastrado</div>
                <?php endif; ?>
            </div>
        </div>
    </div>
    <div class="col-lg-12">
        <div class="panel panel-info">
            <div class="panel-heading"><span class="text-blue">Categorias/Orçamento</span></div>
            <div class="panel-body">
                <?php if ($this->isConta) : ?>
                <div class="col-lg-6" id="dados-categorias"></div>
                <div class="col-lg-6" id="dados-orcamentos"></div>
                <?php else : ?>
                <div class="text-warning">Nenhum registro encontrado.</div>
                <?php endif; ?>
            </div>
        </div>
    </div>
    <div class="col-lg-6">
        <div class="panel panel-success">
            <div class="panel-heading">
                <span class="text-green">Próximas Receitas</span>
                <span class="small">(Máx. 5 registros)</span>
            </div>
            <div class="panel-body">
                <?php if ($this->receitas->count() > 0) : ?>
                    <table class="table table-striped">
                        <tr>
                            <th>Data</th>
                            <th>Descrição</th>
                            <th>Valor</th>
                            <th>Ações</th>
                        </tr>
                        <?php foreach ($this->receitas as $receita) : ?>
                        <tr class="text-green">
                            <td><?php echo View_Helper_Date::getDataView($receita->data_movimentacao); ?></td>
                            <td><?php echo $receita->descricao_movimentacao; ?></td>
                            <td class="text-right"><?php echo View_Helper_Currency::getCurrency($receita->valor_movimentacao); ?></td>
                            <td>
                                <a href="">
                                    <img class="margin-0px-5px" src="<?php echo $this->baseUrl('views/img/icon_edit.png'); ?>" width="20" title="Editar" />
                                </a>
                                <a href="">
                                    <img class="margin-0px-5px" src="<?php echo $this->baseUrl('views/img/icon_delete.png'); ?>" width="20" title="Excluir" />
                                </a>
                            </td>
                        </tr>
                        <?php endforeach; ?>
                    </table>
                <?php else : ?>
                <div class="text-warning">Nenhum registro encontrado.</div>
                <?php endif; ?>
            </div>
        </div>
    </div>
    <div class="col-lg-6">
        <div class="panel panel-danger">
            <div class="panel-heading">
                <span class="text-red">Próximas Despesas</span>
                <span class="small">(Máx. 5 registros)</span>                
            </div>
            <div class="panel-body">
                <?php if ($this->despesas->count() > 0) : ?>
                    <table class="table table-striped">
                        <tr>
                            <th>Data</th>
                            <th>Descrição</th>
                            <th>Valor</th>
                            <th>Ações</th>
                        </tr>
                        <?php foreach ($this->despesas as $despesa) : ?>
                        <tr class="text-red">
                            <td><?php echo View_Helper_Date::getDataView($despesa->data_movimentacao); ?></td>
                            <td><?php echo $despesa->descricao_movimentacao; ?></td>
                            <td class="text-center"><?php echo View_Helper_Currency::getCurrency($despesa->valor_movimentacao); ?></td>
                            <td>
                                <a href="">
                                    <img class="margin-0px-5px" src="<?php echo $this->baseUrl('views/img/icon_edit.png'); ?>" width="20" title="Editar" />
                                </a>
                                <a href="">
                                    <img class="margin-0px-5px" src="<?php echo $this->baseUrl('views/img/icon_delete.png'); ?>" width="20" title="Excluir" />
                                </a>
                            </td>
                        </tr>
                        <?php endforeach; ?>
                    </table>
                <?php else : ?>
                <div class="text-warning">Nenhum registro encontrado.</div>
                <?php endif; ?>
            </div>
        </div>
    </div>
        
    <!-- Modal de Graficos -->
    <div class="modal fade" id="modalGraficosLancamentos" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                    <h4 class="modal-title" id="myModalLabel">Gráfico Lançamentos</h4>
                </div>
                <div class="modal-body" id="grafico-receitas-despesas"></div>
            </div>
        </div>
    </div>
    
    <!-- Modal de Saldo de contas -->
    <div class="modal" id="modalSaldoContas" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                    <h3 class="modal-title text-success" id="myModalLabel">Saldo</h3>
                </div>
                <div class="modal-body" id="saldo-contas">
                    <table class="table table-striped table-responsive bold">
                        <tr>
                            <th class="text-blue">CONTA/TIPO</th>
                            <th class="text-blue text-right">SALDO</th>
                        </tr>
                        <?php foreach ($this->saldos as $saldo) : ?>
                        <tr>
                            <td>
                                <?php echo $saldo->descricao_conta; ?>
                                <p class="small text-muted"><?php echo $saldo->descricao_tipo_conta; ?></p>
                            </td>
                            <td class="text-right <?php echo $saldo->saldo > 0 ? 'text-success' : 'text-danger'; ?>">
                                <?php echo View_Helper_Currency::getCurrency($saldo->saldo); ?>
                            </td>
                        </tr>
                        <?php endforeach; ?>                        
                    </table>                    
                </div>
                <div class="modal-footer">
                    <div class="col-lg-6 pull-right">
                        <table class="table bold large">
                            <tr>
                                <td>TOTAL:</td>
                                <td class="<?php echo $saldo->saldo > 0 ? 'text-success' : 'text-danger'; ?>">
                                    <?php echo View_Helper_Currency::getCurrency($this->saldo_total); ?>
                                </td>
                            </tr>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>