<div class="row">    
    <div class="col-lg-12">    
        <?php echo View_Helper_Messages::render($this->messages); ?> 
        <div class="panel panel-info">
            <div class="panel-heading">Lançamento Fatura</div>
            <div class="panel-body">
                <table class="table table-striped table-responsive">
                    <thead>
                        <tr>
                            <th>Data</th>
                            <th>Descrição</th> 
                            <th>Categoria</th> 
                            <th>Valor</th>
                        </tr>
                    </thead>
                    <?php if ($this->lancamentos->count() > 0) : ?>
                    <tbody>
                        <?php foreach ($this->lancamentos as $lancamento) : ?>
                        <tr>
                            <td><?php echo View_Helper_Date::getDataView($lancamento->data_movimentacao); ?></td>
                            <td><?php echo $lancamento->descricao_movimentacao; ?></td>
                            <td><?php echo $lancamento->descricao_categoria; ?></td>
                            <td class="text-right bold <?php echo $lancamento->valor_movimentacao > 0 ? 'text-success' : 'text-danger'; ?>">                                
                                <?php echo View_Helper_Currency::getCurrency($lancamento->valor_movimentacao); ?>
                            </td>
                        </tr>
                        <?php endforeach; ?>
                        <tr class="text-right bold">
                            <td colspan="3">TOTAL FATURA</td>
                            <td><?php echo View_Helper_Currency::getCurrency($this->total_fatura); ?></td>
                        </tr>
                    </tbody>
                    <?php endif; ?>
                </table>                    
            </div>
        </div>
    </div>
</div>