<?php echo $this->headScript()->appendFile($this->baseUrl('views/js/movimentacoes/transferencia.js')); ?>
<div id="pages">
    <div id="movimentacoes-transferencia">        
        <fieldset style="border-color: #1d5fa1">
            <legend style="color: #1d5fa1"><b>Nova Transferência</b></legend>
            <?php echo $this->formMovimentacaoTransferencia; ?>
        </fieldset>        
    </div>
</div>