<html>
    <body>
        <div style="float: left; width: 70%; margin: 10px 15%; border: 1px solid #696969; padding: 0 7px;">
            <div style="float: left; width: 100%;">
                <img style="padding: 15px; width: 250px;" src="http://newfinances.com.br/views/img/logo_newfinances.png" />
                <div style="float: left; width: 100%; padding: 7px;">
                    <h2 style="text-align: center; margin: 10px 0;">AVISO IMPORTANTE</h2 >
                    <h3>Olá <?php echo $this->dados->nome_completo; ?>,</h3>
                    <p style="color: red;"><i>Já faz muito tempo que você não acessa o sistema!</i></p>                    
                    <p>
                        Caso tenha havido algum problema, insatisfação ou se você 
                        quiser nos dar alguma sugestão 
                        <a href="http://newfinances.com.br/contato"> clique aqui </a>
                        e entre em contato conosco.
                    </p>                    
                </div>
            </div>
            <div style="position: relative; bottom: 0; left: 0;">
                <p style="text-align: center;">E-mail gerado automaticamente. Por favor não responda ao mesmo.</p>
                <p style="font-size: 12px; margin-top: 13px;">Atenciosamente,</p>
                <p style="font-weight: bold; font-size: 12px; margin-bottom: 7px;">Equipe NewFinances - contato@newfinances.com.br</p>        
            </div>
        </div>
    </body>
</html>