<div class="row">    
    <?php echo View_Helper_Messages::render($this->messages); ?>
    <div class="panel panel-info">
        <div class="panel-heading">
            Funcionalidades
            <div class="pull-right">
                <a href="<?php echo $this->url(array(
                    'module' => 'admin',
                    'controller' => 'funcionalidade',
                    'action' => 'nova-funcionalidade'
                ), null, true); ?>">
                    <img src="<?php echo $this->baseUrl('views/img/icon_add.png'); ?>" width="25px" title="Cadastrar Nova Funcionalidade"/>
                </a>
            </div>
        </div>
        <div class="panel-body">
            <table class="table table-striped table-responsive">
                <thead>
                    <tr>
                        <th>Descrição</th>
                        <th>Módulo</th>
                        <th>Controller</th>
                        <th>Action</th>
                        <th>Autenticação</th>
                        <th>Ações</th>
                    </tr>
                </thead>
                <tbody>
                <?php if ($this->funcionalidades->count() > 0) : ?>
                    <?php foreach ($this->funcionalidades as $funcionalidade) : ?>
                    <tr>
                        <td><?php echo $funcionalidade->descricao_permissao; ?></td>
                        <td><?php echo $funcionalidade->module; ?></td>
                        <td><?php echo $funcionalidade->controller; ?></td>
                        <td><?php echo $funcionalidade->action; ?></td>
                        <td><?php echo $funcionalidade->auth == 1 ? 'Sim' : 'Não'; ?></td>
                        <td class="col-md-1 text-center">
                            <a href="<?php echo $this->url(array(
                                'module' => 'admin',
                                'controller' => 'funcionalidade',
                                'action' => 'editar-funcionalidade',
                                'id_funcionalidade' => $funcionalidade->id_funcionalidade
                            )); ?>">
                                <img class="margin-0px-5px" src="<?php echo $this->baseUrl('views/img/icon_edit.png'); ?>" width="20" title="Editar" />
                            </a>
                            <a href="<?php echo $this->url(array(
                                'module' => 'admin',
                                'controller' => 'funcionalidade',
                                'action' => 'excluir-funcionalidade',
                                'id_funcionalidade' => $funcionalidade->id_funcionalidade
                            )); ?>">
                                <img class="margin-0px-5px" src="<?php echo $this->baseUrl('views/img/icon_delete.png'); ?>" width="20" title="Excluir" />
                            </a>
                        </td>
                    </tr>
                    <?php endforeach; ?>
                <?php else : ?>
                    <tr>
                        <td>Nenhuma funcionalidade cadastrada</td>
                    </tr>
                <?php endif; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>