<div class="row">
    <div class="col-lg-12">
        <?php echo View_Helper_Messages::render($this->messages); ?>
        <div class="panel panel-info">
            <div class="panel-heading">Nova Funcionalidade</div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-lg-6"><?php echo $this->formAdminFuncionalidadeCadastro; ?></div>
                </div>
            </div>
        </div>
    </div>
</div>