<div class="col-lg-12">
    <p><h3 class="text-green">Faça Seu Cadastro</h3></p>
<?php echo View_Helper_Messages::render($this->messages); ?>
</div>
<div class="col-lg-5">
    <!--<img class="img-banner" src="<?php echo $this->baseUrl('views/img/img_cadastre-se.jpg'); ?>" />-->
    <p class="margin-top-10px text-justify">

    </p>
    <p>
        Para realizar seu cadastro preencha todos os campos ao lado. É prático,
        rápido e <span class="text-success bold">gratuito.</span>
    </p>
    <p class="text-justify">        
        Desde já a equipe <label class="text-blue">NewFinances</label> lhe dá as
        boas vindas.
    </p>
    <div role="tabpanel">
        <!-- Nav tabs -->
        <ul class="nav nav-tabs" role="tablist">
            <li role="presentation" class="active" class="text-success" >
                <a class="text-success" href="#privacidade" aria-controls="home" role="tab" data-toggle="tab">Política de Privacidade</a>
            </li>
            <li role="presentation"class="text-success" >
                <a class="text-success" href="#uso" aria-controls="profile" role="tab" data-toggle="tab">Política de Uso</a>
            </li>        
        </ul>
        <!-- Tab panes -->
        <div class="tab-content">
            <div role="tabpanel" class="tab-pane active" id="privacidade">...</div>
            <div role="tabpanel" class="tab-pane" id="uso">...</div>
        </div>

    </div>
</div>
<div class="col-lg-1">&nbsp;</div>
<div class="col-lg-6">    
    <?php echo $this->formSiteCadastro; ?>
</div>