<div class="col-lg-12">
    <p><h3 class="text-green">Faça Seu Cadastro</h3></p>
</div>
<div class="col-lg-5">
    <img class="img-banner" src="<?php echo $this->baseUrl('views/img/img_cadastre-se.jpg'); ?>" />
    <p class="margin-top-10px text-justify">
        
    </p>
    <p class="text-justify">
        Desde já a equipe <label class="text-blue">NewFinances</label> lhe dá as
        boas vindas.
    </p>
</div>
<div class="col-lg-1">&nbsp;</div>
<div class="col-lg-6">    
    <?php echo $this->formSiteCadastro; ?>
</div>