<html>
    <body>
        <div style="float: left; width: 70%; margin: 10px 15%; border: 1px solid #696969; padding: 0 7px;">
            <div style="float: left; width: 100%;">
                <img style="padding: 15px; width: 250px;" src="http://newfinances.com.br/views/img/logo_newfinances.png" />
                <div style="float: left; width: 100%; padding: 7px;">
                    <h2 style="text-align: center; margin: 10px 0;">Lembrete de Lançamento a vencer</h2 >
                    <h3>Olá <?php echo $this->lancamento->nome_completo; ?>,</h3>
                    <p><i>Segue abaixo um lembrete de um lançamento que irá vencer nos próximos dias. Fique atento!</i></p>
                    <p>Data: <?php echo View_Helper_Date::getDataView($this->lancamento->data_movimentacao); ?></p>
                    <p>Descrição: <?php echo $this->lancamento->descricao_movimentacao; ?></p>                
                    <p>Valor: <?php echo View_Helper_Currency::getCurrency($this->lancamento->valor_movimentacao); ?></p>                
                    <p>Categoria: <?php echo $this->lancamento->descricao_categoria; ?></p>                
                </div>
            </div>
            <div style="position: relative; bottom: 0; left: 0;">
                <p style="text-align: center;">E-mail gerado automaticamente. Por favor não responda ao mesmo.</p>
                <p style="font-size: 12px; margin-top: 13px;">Atenciosamente,</p>
                <p style="font-weight: bold; font-size: 12px; margin-bottom: 7px;">Equipe NewFinances - contato@newfinances.com.br</p>        
            </div>
        </div>
    </body>
</html>