<div class="row">
    <div class="col-lg-12">
        <?php echo View_Helper_Messages::render($this->messages); ?>
        <div class="panel panel-info">
            <div class="panel-heading">Meus Chamados</div>
            <div class="panel-body">
                <ul class="nav nav-tabs" role="tablist">                    
                    <li class="active">
                        <a href="#abertos" role="tab" data-toggle="tab">
                            <span class="text-danger">Chamados Abertos</span>
                            <span class="badge"><?php echo $this->chamados_abertos->count(); ?></span>
                        </a>
                    </li>                  
                    <li>
                        <a href="#fechados" role="tab" data-toggle="tab">
                            <span class="text-success">Chamados Fechados</span>
                            <span class="badge"><?php echo $this->chamados_finalizados->count(); ?></span>
                        </a>
                    </li>
                </ul>
                
                <div class="tab-content">
                    <div class="col-lg-12 border-left border-right border-bottom">
                        <div class="tab-pane fade in active" id="abertos">  
                            <?php if ($this->chamados_abertos->count() > 0) : ?>
                                <table class="table table-responsive table-striped margin-top-10px">
                                    <tr>
                                        <th>Abertura</th>
                                        <th>Tipo</th>
                                        <th>Assunto</th>
                                        <th>Respostas</th>
                                        <th>Ações</th>
                                    </tr>
                                    <?php foreach ($this->chamados_abertos as $chamado) : ?>
                                        <tr>
                                            <td><?php echo View_Helper_Date::getDataView($chamado->data_abertura); ?></td>
                                            <td><?php echo $chamado->descricao; ?></td>
                                            <td><?php echo $chamado->assunto; ?></td>
                                            <td></td>
                                            <td>

                                            </td>
                                        </tr>
                                    <?php endforeach; ?>
                                </table>
                            <?php else : ?>
                                <div class="text-warning padding-10px-0">Nenhum chamado aberto</div>
                            <?php endif; ?>
                        </div>
                        <div class="tab-pane fade" id="fechados">
                            <?php if ($this->chamados_finalizados->count() > 0) : ?>
                                <table class="table table-responsive table-striped">
                                    <tr>
                                        <th>Abertura</th>
                                        <th>Tipo</th>
                                        <th>Assunto</th>
                                        <th>Ações</th>
                                    </tr>
                                    <?php foreach ($this->chamados_finalizados as $chamado) : ?>
                                        <tr>
                                            <td><?php echo $chamado->data_abertura; ?></td>
                                            <td><?php echo $chamado->descricao; ?></td>
                                            <td><?php echo $chamado->assunto; ?></td>
                                            <td>

                                            </td>
                                        </tr>
                                    <?php endforeach; ?>
                                </table>
                            <?php else : ?>
                                <div class="text-warning padding-10px-0">Nenhum chamado fechado</div>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>
                
            </div>
        </div>
    </div>
</div>