<?php

$container = new Zend_Navigation();
$this->navigation($container);

$container->addPage(
    array(
        'label' => 'Início',
        'module' => 'cliente',
        'controller' => 'index',
        'action' => 'index',
        'pages' => array(
            array(
                'label' => 'Movimentações',
                'module' => 'cliente',
                'controller' => 'index',
                'action' => 'index',
                'pages' => array(
                    array(
                        'label' => 'Nova Despesa',
                        'module' => 'cliente',
                        'controller' => 'movimentacoes',
                        'action' => 'nova-despesa',
                    ),
                    array(
                        'label' => 'Nova Receita',
                        'module' => 'cliente',
                        'controller' => 'movimentacoes',
                        'action' => 'nova-receita',
                    ),
                    array(
                        'label' => 'Transferência',
                        'module' => 'cliente',
                        'controller' => 'movimentacoes',
                        'action' => 'transferencia',
                    )
                )
            ),            
            array(
                'label' => 'Orçamentos',
                'module' => 'cliente',
                'controller' => 'orcamentos',
                'action' => 'index',
                'pages' => array(
                    array(
                        'label' => 'Novo Orçamento',
                        'module' => 'cliente',
                        'controller' => 'orcamentos',
                        'action' => 'novo-orcamento'
                    )
                )
            ),
            array(
                'label' => 'Categorias',
                'module' => 'cliente',
                'controller' => 'categorias',
                'action' => 'index',
                'pages' => array(
                    array(
                        'label' => 'Nova Categoria',
                        'module' => 'cliente',
                        'controller' => 'categorias',
                        'action' => 'nova-categoria'
                    ),
                    array(
                        'label' => 'Editar Categoria',
                        'module' => 'cliente',
                        'controller' => 'categorias',
                        'action' => 'editar'
                    )
                )
            )
        )
    )    
);

echo '<div class="row"><div class="col-lg-12 small"><div class="thumbnail"><span>Você está em: </span>';
echo $this->navigation()->breadcrumbs()->setLinkLast(false)->setMinDepth(0)->render();
echo '</div></div></div>';