<?php

$container = new Zend_Navigation();
$this->navigation($container);

$container->addPage(
    array(
        'label' => 'Movimentações',
        'module' => 'cliente',
        'controller' => 'index',
        'action' => 'index',
        'pages' => array(
            array(
                'label' => 'Nova Despesa',
                'module' => 'cliente',
                'controller' => 'movimentacoes',
                'action' => 'nova-despesa',
            ),
            array(
                'label' => 'Nova Receita',
                'module' => 'cliente',
                'controller' => 'movimentacoes',
                'action' => 'nova-receita',
            ),
            array(
                'label' => 'Transferência',
                'module' => 'cliente',
                'controller' => 'movimentacoes',
                'action' => 'transferencia',
            )
        )
    ) 
);

echo '<div class="row"><div class="col-lg-12 text-muted small"><div class="thumbnail"><span>Você está em: </span>';
echo $this->navigation()->breadcrumbs()->setLinkLast(false)->setMinDepth(0)->render();
echo '</div></div></div>';