<?php $identity = Zend_Auth::getInstance()->hasIdentity(); ?>
<?php $auth = Zend_Auth::getInstance()->getIdentity(); ?>
<?php

    $namePart = explode(" ", $auth->nome_completo);    
    foreach ($namePart as $key => $value) {
        $short_name = $namePart[0] . ' ';        
        if ($key + 1 == count($namePart)) {
            $short_name .= $value;
        }
    }

?>
<div class="container">                                
    <ul class="nav navbar-nav">                    
        <li class="active"><a href="<?php
            echo $this->url(array(
                'module' => 'cliente',
                'controller' => 'index',
                'action' => 'index'
            ), null, true);
            ?>">Início</a></li>
        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Lançamentos <b class="caret"></b></a>
            <ul class="dropdown-menu">
                <li><a href="<?php echo $this->url(array(
                    'module' => 'cliente',
                    'controller' => 'movimentacoes',
                    'action' => 'nova-receita'
                ), null, true); ?>">Nova Receita</a></li>
                <li><a href="<?php echo $this->url(array(
                    'module' => 'cliente',
                    'controller' => 'movimentacoes',
                    'action' => 'nova-despesa'
                ), null, true); ?>">Nova Despesa</a></li>
                <li><a href="<?php echo $this->url(array(
                    'module' => 'cliente',
                    'controller' => 'movimentacoes',
                    'action' => 'transferencia'
                ), null, true); ?>">Transferência</a></li>
            </ul>
        </li>
        <li class="active"><a href="<?php echo $this->url(array(
            'module' => 'cliente',
            'controller' => 'orcamentos',
            'action' => 'index'
        ), null, true); ?>">Orçamentos</a></li>
        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Relatórios <b class="caret"></b></a>
            <ul class="dropdown-menu">
                <li><a href="<?php echo $this->url(array()); ?>">Anual</a></li>
            </ul>
        </li>
        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Contas/Cartão <b class="caret"></b></a>
            <ul class="dropdown-menu">
                <li><a href="<?php echo $this->url(array()); ?>">Nova Conta</a></li>
                <li><a href="<?php echo $this->url(array()); ?>">Novo Cartão</a></li>
            </ul>
        </li>
        <li class="active"><a href="<?php echo $this->url(array()); ?>">Meus Chamados</a></li>
    </ul>               
    <ul class="nav navbar-nav navbar-right">                    
        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><?php echo $short_name; ?> <b class="caret"></b></a>
            <ul class="dropdown-menu">
                <li><a href="<?php
                    echo $this->url(array(
                        'module' => 'cliente',
                        'controller' => 'meusdados',
                        'action' => 'index'
                    ), null, true);
                    ?>">Meus Dados</a></li>
                <li class="divider"></li>
                <li><a href="<?php
                    echo $this->url(array(
                        'module' => 'cliente',
                        'controller' => 'usuarios',
                        'action' => 'logout'
                    ), null, true);
                    ?>">Sair</a></li>
            </ul>
        </li>
    </ul>               
</div>