<?php $identity = Zend_Auth::getInstance()->hasIdentity(); ?>
<?php $auth = Zend_Auth::getInstance()->getIdentity(); ?>
<?php

    $namePart = explode(" ", $auth->nome_completo);    
    foreach ($namePart as $key => $value) {
        $short_name = $namePart[0] . ' ';        
        if ($key + 1 == count($namePart)) {
            $short_name .= $value;
        }
    }

?>

<!DOCTYPE html>
<html lang="pt-BR">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="">
        <meta name="author" content="">

        <title>NewFinances</title>

        <?php echo $this->headScript()->appendFile($this->baseUrl('views/js/jquery-1.10.2.js')); ?>
        <?php echo $this->headScript()->appendFile($this->baseUrl('views/js/bootstrap.js')); ?>
        
        <!-- Bootstrap core CSS -->
        <link href="<?php echo $this->baseUrl('views/css/bootstrap.css'); ?>" rel="stylesheet">
        <!-- Custom CSS for the 'Business Frontpage' Template -->
        <link href="<?php echo $this->baseUrl('views/css/business-frontpage.css'); ?>" rel="stylesheet">
        <!-- Custom CSS for layout -->
        <link href="<?php echo $this->baseUrl('views/css/layout.css'); ?>" rel="stylesheet">
        
    </head>

    <body id="body">
        <nav class="navbar navbar-fixed-top background-color-blue" role="navigation">            
            <div class="container">                
                <ul class="nav navbar-nav">                    
                    <li class="active"><a href="<?php echo $this->url(array(
                        'module' => 'cliente',
                        'controller' => 'index',
                        'action' => 'index'
                    )); ?>">Início</a></li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Lançamentos <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                           <li><a href="#">Nova Receita</a></li>
                           <li><a href="#">Nova Despesa</a></li>
                           <li><a href="#">Transferência</a></li>
                        </ul>
                    </li>
                    <li class="active"><a href="#">Orçamentos</a></li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Relatórios <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                           <li><a href="#">Anual</a></li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Contas/Cartão <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                           <li><a href="#">Nova Conta</a></li>
                           <li><a href="#">Novo Cartão</a></li>
                        </ul>
                    </li>
                    <li class="active"><a href="#">Meus Chamados</a></li>
                </ul>               
                <ul class="nav navbar-nav navbar-right">                    
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><?php echo $short_name; ?> <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                           <li><a href="<?php echo $this->url(array(
                               'module' => 'cliente',
                               'controller' => 'meusdados',
                               'action' => 'index'
                           )); ?>">Meus Dados</a></li>
                           <li class="divider"></li>
                           <li><a href="<?php echo $this->url(array(
                               'module' => 'cliente',
                               'controller' => 'usuarios',
                               'action' => 'logout'
                           )); ?>">Sair</a></li>
                        </ul>
                    </li>
               </ul>               
            </div>
        </nav>                    
        <div class="container">            
            <div class="col-lg-12 col-sm-12">
                <?php echo $this->layout()->content; ?>                    
            </div>             
        </div>
        <footer class="background-color-orange">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <a class="redes-sociais" href="">
                            <img class="img-rounded margin-10px" src="<?php echo $this->baseUrl('views/img/icon_face_social2.png'); ?>" />
                        </a>
                        <a class="redes-sociais" href="">
                            <img class="img-rounded margin-10px" src="<?php echo $this->baseUrl('views/img/icon_twitter_social2.png'); ?>" />
                        </a>
                        <a class="redes-sociais" href="">
                            <img class="img-rounded margin-10px" src="<?php echo $this->baseUrl('views/img/icon_google_plus_social2.png'); ?>" />
                        </a>
                    </div>                                                                          
                </div>   
            </div>            
        </footer>
        <!-- /container -->
    </body>

</html>


