<!DOCTYPE html>
<html lang="pt-BR">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="">
        <meta name="author" content="">

        <title>NewFinances</title>

        <!-- Bootstrap core CSS -->
        <link href="<?php echo $this->baseUrl('views/css/bootstrap.css'); ?>" rel="stylesheet">

        <!-- Custom CSS for the 'Business Frontpage' Template -->
        <link href="<?php echo $this->baseUrl('views/css/business-frontpage.css'); ?>" rel="stylesheet">
    </head>

    <body>

        <nav class="navbar navbar-fixed-top navbar-inverse" role="navigation">
            <div class="container">
                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse navbar-ex1-collapse">
                    <ul class="nav navbar-nav">
                        <li><a href="#about">About</a></li>
                        <li><a href="#services">Services</a></li>
                        <li><a href="#contact">Contact</a></li>
                    </ul>
                </div>
                <!-- /.navbar-collapse -->
            </div>
            <!-- /.container -->
        </nav>

        <div class="business-header">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <!-- The background image is set in the custom CSS -->
                        <h1 class="tagline">An Informative Tagline Goes Here</h1>
                    </div>
                </div>
            </div>
        </div>
        <div class="container">
            <hr>
            <div class="row">
                <div class="col-lg-12 col-sm-12">
                    <?php echo $this->layout()->content; ?>                    
                </div>
            </div>
            <hr>            
            <footer>
                <div class="row">
                    <div class="col-lg-12">
                        <p>Copyright &copy; Company 2013</p>
                    </div>
                </div>
            </footer>
        </div>
        <!-- /container -->
    </body>

</html>


