<!DOCTYPE html>
<html lang="pt-BR">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="">
        <meta name="author" content="">

        <title>NewFinances</title>

        <?php echo $this->headScript()->appendFile($this->baseUrl('views/js/jquery-1.10.2.js')); ?>
        <?php echo $this->headScript()->appendFile($this->baseUrl('views/js/bootstrap.js')); ?>
        <?php echo $this->headScript()->appendFile($this->baseUrl('views/js/layout.js')); ?>
        <?php echo $this->headScript()->appendFile($this->baseUrl('views/js/ajax.newsletter.js')); ?>        
        <?php echo $this->headScript()->appendFile($this->baseUrl('views/js/bootstrap-datepicker.js')); ?>
        <?php echo $this->headScript()->appendFile($this->baseUrl('views/js/jquery.maskMoney.js')); ?>
        <?php echo $this->headScript()->appendFile($this->baseUrl('views/js/jquery.maskedinput.js')); ?>
        <?php echo $this->headScript()->appendFile($this->baseUrl('views/js/application.js')); ?>
                
        <!-- Bootstrap core CSS -->
        <link href="<?php echo $this->baseUrl('views/css/bootstrap.css'); ?>" rel="stylesheet">
        <!-- Custom CSS for the 'Business Frontpage' Template -->
        <link href="<?php echo $this->baseUrl('views/css/business-frontpage.css'); ?>" rel="stylesheet">
        <!-- Custom CSS for layout -->
        <link href="<?php echo $this->baseUrl('views/css/layout.css'); ?>" rel="stylesheet">
        <!-- Custom timeline -->
        <link href="<?php echo $this->baseUrl('views/css/timeline.css'); ?>" rel="stylesheet">   
        <!-- Custom themes -->
        <link href="<?php echo $this->baseUrl('views/css/themes.css'); ?>" rel="stylesheet">   
        
    </head>

    <body id="body" class="body-christmas">
        <nav class="navbar navbar-default navbar-fixed-top background-color-blue" role="navigation">
            <div class="container container-fluid">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>

                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">
                        <li><a href="<?php echo $this->url(array(
                                'module' => 'site',
                                'controller' => 'index',
                                'action' => 'index'
                            ), null, true); ?>"><span class="glyphicon glyphicon-home"></span> Início</a></li>    
                        <!--
                        <li><a href="<?php echo $this->url(array(
                                'module' => 'site',
                                'controller' => 'sistema',
                                'action' => 'index'
                        ), null, true); ?>"><span class="glyphicon glyphicon-th-large"></span> O Sistema</a></li>                          
                        <li><a href="<?php echo $this->url(array(
                                'module' => 'site',
                                'controller' => 'planos',
                                'action' => 'index'
                        ), null, true); ?>">Planos</a></li>  
                        
                        <li><a href="<?php echo $this->url(array(
                                'module' => 'site',
                                'controller' => 'contato',
                                'action' => 'index'
                        ), null, true); ?>"><span class="glyphicon glyphicon-user"></span> Faça Contato</a></li>  
                        -->
                    </ul>                                     
                    
                </div><!-- /.navbar-collapse -->
            </div><!-- /.container-fluid -->
        </nav>           
        
        <div class="container container-fluid">            
            <div class="">
                <div class="col-lg-12 background-color-white">    
                    <hr />
                    <?php echo $this->layout()->content; ?>                    
                </div>           
            </div>
        </div>
        <footer>  
            <div class="col-lg-12 background-color-orange">
                <div class="container container-fluid">
                    <div class="row">
                        <div class="col-lg-4 text-left small text-white">contato@newfinances.com.br</div>
                        <div class="col-lg-4 text-center">
                            <a class="img redes-sociais" href="https://www.facebook.com/sisnewfinances" target="_blank">
                                <img class="redes-sociais img-rounded" src="<?php echo $this->baseUrl('views/img/icon_face_social.png'); ?>" />
                            </a>
                            <a class="img redes-sociais" href="https://twitter.com/NewFinances" target="_blank">
                                <img class="redes-sociais" src="<?php echo $this->baseUrl('views/img/icon_twitter_social.png'); ?>" />
                            </a>
                            <a class="img redes-sociais" href="https://plus.google.com/104418631172971802903/posts" target="_blank">
                                <img class="redes-sociais" src="<?php echo $this->baseUrl('views/img/icon_google_plus_social.png'); ?>" />
                            </a>
                        </div>
                        <div class="col-lg-4 text-right small text-white">Copyright NewFinances. Todos os direitos reservados</div>
                    </div>
                </div>        
            </div>            
        </footer>
        <!-- /container -->
    </body>
    <div id="fb-root"></div>    
</html>


