<!DOCTYPE html>
<html lang="pt-BR">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="">
        <meta name="author" content="">

        <title>NewFinances</title>

        <?php echo $this->headScript()->appendFile($this->baseUrl('views/js/jquery-1.10.2.js')); ?>
        <?php echo $this->headScript()->appendFile($this->baseUrl('views/js/bootstrap.js')); ?>
        <?php echo $this->headScript()->appendFile($this->baseUrl('views/js/layout.js')); ?>
        <?php echo $this->headScript()->appendFile($this->baseUrl('views/js/ajax.newsletter.js')); ?>
        
        <!-- Bootstrap core CSS -->
        <link href="<?php echo $this->baseUrl('views/css/bootstrap.css'); ?>" rel="stylesheet">
        <!-- Custom CSS for the 'Business Frontpage' Template -->
        <link href="<?php echo $this->baseUrl('views/css/business-frontpage.css'); ?>" rel="stylesheet">
        <!-- Custom CSS for layout -->
        <link href="<?php echo $this->baseUrl('views/css/layout.css'); ?>" rel="stylesheet">
        
    </head>

    <body id="body">
        <nav class="navbar navbar-fixed-top background-color-blue" role="navigation">
            <div class="container">
                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse navbar-ex1-collapse">
                    <ul class="nav navbar-nav">
                        <li><a href="<?php echo $this->url(array(
                            'module' => 'site',
                            'controller' => 'index',
                            'action' => 'index'
                        )); ?>">Principal</a></li>
                        <li><a href="<?php echo $this->url(array(
                            'module' => 'site',
                            'controller' => 'sistema',
                            'action' => 'index'
                        )); ?>">O Sistema</a></li>
                        <li><a href="<?php echo $this->url(array(
                            'module' => 'site',
                            'controller' => 'cadastro-usuario',
                            'action' => 'index'
                        )); ?>">Cadastre-se</a></li>                        
                        <li><a href="<?php echo $this->url(array(
                            'module' => 'site',
                            'controller' => 'contato',
                            'action' => 'index'
                        )); ?>">Contato</a></li>                        
                    </ul>
                    <div class="navbar-right padding-top-10px">                         
                        <form method="post" class="form-inline" action="usuarios/login">                            
                            <input class="input-sm form-control" type="text" name="email_usuario" placeholder="e-mail" />                            
                            <input class="input-sm form-control" type="password" name="senha_usuario" placeholder="senha" />
                            <input class="btn btn-sm btn-success" type="submit" name="submit" value="Logar" />
                            <a class="small" href="<?php echo $this->url(array(
                                'module' => 'site',
                                'controller' => 'usuarios',
                                'action' => 'recuperar-senha'
                            )); ?>">Esqueci a senha</a>                                
                        </form>
                    </div>
                </div>                
            </div>            
        </nav>                
        <div class="business-header">              
            <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
                <!-- Indicators -->
                <ol class="carousel-indicators">
                    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
                    <li data-target="#carousel-example-generic" data-slide-to="3"></li>
                    <li data-target="#carousel-example-generic" data-slide-to="4"></li>
                </ol>

                <!-- Wrapper for slides -->
                <div class="carousel-inner">
                    <div class="item active">
                        <img class="img-banner" src="<?php echo $this->baseUrl('views/img/banners/banner_1.png'); ?>" alt="">
                        <div class="carousel-caption"></div>
                    </div>
                    <div class="item">
                        <img class="img-banner" src="<?php echo $this->baseUrl('views/img/banners/banner_2.png'); ?>" alt="">
                        <div class="carousel-caption"></div>
                    </div>
                    <div class="item">
                        <img class="img-banner" src="<?php echo $this->baseUrl('views/img/banners/banner_3.png'); ?>" alt="">
                        <div class="carousel-caption"></div>
                    </div>
                    <div class="item">
                        <img class="img-banner" src="<?php echo $this->baseUrl('views/img/banners/banner_4.png'); ?>" alt="">
                        <div class="carousel-caption"></div>
                    </div>
                    <div class="item">
                        <img class="img-banner" src="<?php echo $this->baseUrl('views/img/banners/banner_5.png'); ?>" alt="">
                        <div class="carousel-caption"></div>
                    </div>
                </div>
                <!-- Controls 
                <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
                    <span class="glyphicon glyphicon-chevron-left"></span>
                </a>
                <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
                    <span class="glyphicon glyphicon-chevron-right"></span>
                </a>
                -->
            </div>
            <div class="bg-banner"></div>
            <div class="row-container-logo">
                <div class="container container-logo">
                    <img class="img-responsive logo" src="<?php echo $this->baseUrl('views/img/logo_newfinances.png'); ?>" width="300"/>            
                </div>
            </div>            
        </div>
        <div class="container">
            <div class="row">
                <div class="col-lg-12 col-sm-12">
                    <?php echo $this->layout()->content; ?>                    
                </div>                
            </div>
            
            <hr>            
        </div>
        <footer class="background-color-orange">
            <div class="container">
                <div class="row">
                    <div class="col-lg-4">
                        <p class="margin-10px text-blue"><b>Acesse nossas redes sociais:</b></p>
                        <a class="redes-sociais" href="">
                            <img class="img-rounded margin-10px" src="<?php echo $this->baseUrl('views/img/icon_face_social2.png'); ?>" />
                        </a>
                        <a class="redes-sociais" href="">
                            <img class="img-rounded margin-10px" src="<?php echo $this->baseUrl('views/img/icon_twitter_social2.png'); ?>" />
                        </a>
                        <a class="redes-sociais" href="">
                            <img class="img-rounded margin-10px" src="<?php echo $this->baseUrl('views/img/icon_google_plus_social2.png'); ?>" />
                        </a>
                        <p>
                            <h5 class="text-blue margin-10px"><b>Mapa do Site</b></h5>
                        </p>
                        <ul class="footer">
                            <li><a href="">Página principal</a></li>
                            <li><a href="">Sobre o sistema</a></li>
                            <li><a href="">Faça o seu cadastro</a></li>
                            <li><a href="">Faça contato</a></li>
                        </ul>                        
                    </div>              
                    <div class="col-lg-3">
                        <div class="row" id="form-newsletter">
                            <p class="margin-top-10px text-blue"><b>NewsLetter:</b></p>
                            <p>
                                Assine nossa newsletter e receba notícias e
                                promoções.
                            </p>                            
                            <table class="table table-responsive">
                                <tr>
                                    <td><input class="input-sm form-control" type="text" name="nome" id="nome-news" placeholder="Digite seu nome" /></td>
                                    <td><input class="input-sm form-control" type="text" name="email" id="email-news" placeholder="Digite seu e-mail" /></td>
                                </tr>
                                <tr>
                                    <td colspan="2" class="">
                                        <button class="btn btn-sm btn-submit" name="bt-newsletter" id="btn-newsletter">Assinar</button>
                                    </td>
                                </tr>
                                <tr>
                                    <td>&nbsp;</td>
                                </tr>
                            </table>                            
                        </div>
                        <div class="row padding-10px margin-top-10px" id="newsletter-loader" style="display: none">
                            <img class="img-responsive center-block" src="<?php echo $this->baseUrl('views/img/loader.gif'); ?>" />
                        </div>
                        <div class="row" id="newsletter-result" style="display: none"></div>
                        <div class="row">
                            <p class="text-blue"><b>Nossa Políticas:</b></p>
                            <p class="">
                                <a href="">Termo de Uso</a> | 
                                <a href="">Política de Privacidade</a>
                            </p>
                            <p class="text-blue"><b>Contato:</b></p>
                            <p class="">
                                <a href="">contato@newfinances.com.br</a>
                            </p>
                        </div>
                    </div>
                    <div class="col-lg-2"></div>
                    <div class="col-lg-3 margin-top-10px">                                                
                        <div class="row">
                            <div id="fb-root"></div>                        
                            <script>
                                (function(d, s, id) {
                                    var js, fjs = d.getElementsByTagName(s)[0];
                                    if (d.getElementById(id))
                                        return;
                                    js = d.createElement(s);
                                    js.id = id;
                                    js.src = "//connect.facebook.net/pt_BR/all.js#xfbml=1";
                                    fjs.parentNode.insertBefore(js, fjs);
                                }(document, 'script', 'facebook-jssdk'));
                            </script>
                            <div class="fb-like-box background-color-white navbar-right" style="width: 100%; margin: 10px 0;"
                                 data-href="http://www.facebook.com/sisnewfinances" 
                                 data-colorscheme="light"                                                               
                                 data-header="false" 
                                 fb-xfbml-state="rendered"
                                 data-show-faces="true" 
                                 data-header="true" 
                                 data-stream="false" 
                                 data-show-border="false">                
                            </div>
                        </div>
                        <div class="row">
                            <a class="twitter-timeline" href="https://twitter.com/NewFinances" data-widget-id="423853342851223552">Tweets de @NewFinances</a>
                            <script>
                                !function(d,s,id){
                                    var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';
                                    if(!d.getElementById(id)){
                                        js=d.createElement(s);
                                        js.id=id;js.src=p+"://platform.twitter.com/widgets.js";
                                        fjs.parentNode.insertBefore(js,fjs);
                                    }
                                }(document,"script","twitter-wjs");
                            </script>
                        </div>
                    </div>
                </div>
            </div>            
        </footer>
        <!-- /container -->
    </body>

</html>


