<!DOCTYPE html>
<html lang="pt-BR">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="">
        <meta name="author" content="">

        <title>NewFinances</title>

        <?php echo $this->headScript()->appendFile($this->baseUrl('views/js/jquery-1.10.2.js')); ?>
        <?php echo $this->headScript()->appendFile($this->baseUrl('views/js/bootstrap.js')); ?>
        <?php echo $this->headScript()->appendFile($this->baseUrl('views/js/layout.js')); ?>
        <?php echo $this->headScript()->appendFile($this->baseUrl('views/js/ajax.newsletter.js')); ?>        
        <?php echo $this->headScript()->appendFile($this->baseUrl('views/js/bootstrap-datepicker.js')); ?>
        <?php echo $this->headScript()->appendFile($this->baseUrl('views/js/jquery.maskMoney.js')); ?>
        <?php echo $this->headScript()->appendFile($this->baseUrl('views/js/jquery.maskedinput.js')); ?>
        <?php echo $this->headScript()->appendFile($this->baseUrl('views/js/application.js')); ?>
                
        <!-- Bootstrap core CSS -->
        <link href="<?php echo $this->baseUrl('views/css/bootstrap.css'); ?>" rel="stylesheet">
        <!-- Custom CSS for the 'Business Frontpage' Template -->
        <link href="<?php echo $this->baseUrl('views/css/business-frontpage.css'); ?>" rel="stylesheet">
        <!-- Custom CSS for layout -->
        <link href="<?php echo $this->baseUrl('views/css/layout.css'); ?>" rel="stylesheet">
        <!-- Custom timeline -->
        <link href="<?php echo $this->baseUrl('views/css/timeline.css'); ?>" rel="stylesheet">   
        <!-- Custom themes -->
        <link href="<?php echo $this->baseUrl('views/css/themes.css'); ?>" rel="stylesheet">   
        
    </head>

    <body id="body" class="body-christmas">
        <nav class="navbar navbar-default navbar-fixed-top background-color-blue" role="navigation">
            <div class="container container-fluid">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>

                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">
                        <li><a href="<?php echo $this->url(array(
                                'module' => 'site',
                                'controller' => 'index',
                                'action' => 'index'
                            ), null, true); ?>"><span class="glyphicon glyphicon-home"></span> Início</a></li>    
                        <!--
                        <li><a href="<?php echo $this->url(array(
                                'module' => 'site',
                                'controller' => 'sistema',
                                'action' => 'index'
                        ), null, true); ?>"><span class="glyphicon glyphicon-th-large"></span> O Sistema</a></li>                          
                        <li><a href="<?php echo $this->url(array(
                                'module' => 'site',
                                'controller' => 'planos',
                                'action' => 'index'
                        ), null, true); ?>">Planos</a></li>  
                        -->
                        <li><a href="<?php echo $this->url(array(
                                'module' => 'site',
                                'controller' => 'contato',
                                'action' => 'index'
                        ), null, true); ?>"><span class="glyphicon glyphicon-user"></span> Faça Contato</a></li>                        
                    </ul>
                    <div class="navbar-form navbar-right">
                        <a class="btn btn-sm btn-success" href="<?php echo $this->url(array(
                                'module' => 'site',
                                'controller' => 'cadastro-usuario',
                                'action' => 'index'
                        ), null, true); ?>"><span class="glyphicon glyphicon-new-window"></span> Cadastre-se</a>
                        <a class="btn btn-sm btn-info" href="<?php echo $this->url(array(
                                'module' => 'site',
                                'controller' => 'usuarios',
                                'action' => 'login'
                        ), null, true); ?>"><span class="glyphicon glyphicon-log-in"></span> Acesse o sistema</a>
                    </div>
                    <!--
                    <form class="navbar-form navbar-right" method="post" action="<?php echo $this->baseUrl('usuarios/login'); ?>">
                        <input class="input-sm form-control" type="text" name="email_usuario" placeholder="e-mail" />                            
                        <input class="input-sm form-control" type="password" name="senha_usuario" placeholder="senha" />
                        <input class="btn btn-sm btn-success" type="submit" name="submit" value="Logar" />
                        <a class="small" href="<?php echo $this->url(array(
                                'module' => 'site',
                                'controller' => 'usuarios',
                                'action' => 'recuperar-senha'
                        )); ?>">Esqueci a senha</a>
                    </form>                    
                    -->
                </div><!-- /.navbar-collapse -->
            </div><!-- /.container-fluid -->
        </nav>           
        <div class="container container-fluid">
            <div class="business-header">              
                <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
                    <!-- Indicators -->                    
                    <ol class="carousel-indicators">
                        <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                        <li data-target="#carousel-example-generic" data-slide-to="1"></li>                        
                        <li data-target="#carousel-example-generic" data-slide-to="2"></li>        
                        
                    </ol>
                    <!-- Wrapper for slides -->
                    <div class="carousel-inner">
                        <div class="item active">
                            <img class="img-banner img-responsive" src="<?php echo $this->baseUrl('views/img/banners/banner_8.png'); ?>" alt="">
                            <div class="carousel-caption slider-text">
                                <h3>Falta de Dinheiro?</h3>
                                <p>Controle suas finanças e adeus bolsos vazios!</p>
                            </div>
                        </div>                        
                        <div class="item">
                            <img class="img-banner img-responsive" src="<?php echo $this->baseUrl('views/img/banners/banner_7.png'); ?>" alt="">
                            <div class="carousel-caption slider-text">
                                <h3>Controle total</h3>
                                <p>Gerencie todas as suas contas, inclusive cartões de crédito</p>
                            </div>
                        </div>
                        <!--
                        <div class="item">
                            <img class="img-banner img-responsive" src="<?php echo $this->baseUrl('views/img/banners/banner_2.png'); ?>" alt="">
                            <div class="carousel-caption slider-text">
                                <h3>First slide label</h3>
                                <p>Lorem ipsum dolor sit amet consectetur…</p>
                            </div>
                        </div>
                        <div class="item">
                            <img class="img-banner img-responsive" src="<?php echo $this->baseUrl('views/img/banners/banner_1.png'); ?>" alt="">
                            <div class="carousel-caption slider-text">
                                <h3>First slide label</h3>
                                <p>Lorem ipsum dolor sit amet consectetur…</p>
                            </div>
                        </div>
                        -->
                        <div class="item">
                            <img class="img-banner img-responsive" src="<?php echo $this->baseUrl('views/img/banners/banner_6.png'); ?>" alt="">
                            <div class="carousel-caption slider-text">
                                <h3>Fique mais tranquilo</h3>
                                <p>Desfrute dos momentos em família sem dor de cabeça e preocupação</p>
                            </div>
                        </div>                        
                    </div>
                    <!-- Controls
                    <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
                        <span class="glyphicon glyphicon-chevron-left"></span>
                    </a>
                    <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
                        <span class="glyphicon glyphicon-chevron-right"></span>
                    </a>                
                     -->
                </div>
                <div class="bg-banner"></div>
                <div class="row-container-logo">
                    <div class="container container-logo">
                        <img class="img-responsive logo" src="<?php echo $this->baseUrl('views/img/logo_newfinances.png'); ?>" width="250"/>            
                    </div>
                </div>            
            </div>
        </div>
        <div class="container container-fluid">            
            <div class="">
                <div class="col-lg-12 background-color-white">    
                    <hr />
                    <?php echo $this->layout()->content; ?>                    
                </div>           
            </div>
        </div>
        <footer>  
            <div class="col-lg-12 background-color-orange">
                <div class="container container-fluid">                    
                    <div class="row">
                        <div class="col-lg-4 text-left small text-white">contato@newfinances.com.br</div>
                        <div class="col-lg-4 text-center">
                            <a class="img redes-sociais" href="https://www.facebook.com/sisnewfinances" target="_blank"><img class="redes-sociais" src="<?php echo $this->baseUrl('views/img/icon_face_social.png'); ?>" /></a>
                            <a class="img redes-sociais" href="https://twitter.com/NewFinances" target="_blank"><img class="redes-sociais" src="<?php echo $this->baseUrl('views/img/icon_twitter_social.png'); ?>" /></a>
                            <a class="img redes-sociais" href="https://plus.google.com/104418631172971802903/posts" target="_blank"><img class="redes-sociais" src="<?php echo $this->baseUrl('views/img/icon_google_plus_social.png'); ?>" /></a>
                        </div>
                        <div class="col-lg-4 text-right small text-white">Copyright NewFinances. Todos os direitos reservados</div>
                    </div>
                </div>        
            </div>            
        </footer>
        <!-- /container -->
    </body>
    <div id="fb-root"></div>    
</html>


