<div class="col-lg-12">
    <?php if ($this->movimentacoes->count() > 0) : ?>
    <table class="table table-striped table-responsive">
        <tr>
            <th class="col-lg-1">Tipo</th> 
            <th class="col-lg-4">Descrição</th> 
            <th class="col-lg-3">Categoria</th> 
            <th class="col-lg-1 text-right">Valor</th> 
            <th class="col-lg-1 text-center">Status</th> 
            <th class="col-lg-2 text-center">Ações</th> 
        </tr>
        <?php foreach ($this->movimentacoes as $movimentacao) : ?>
        <tr class="<?php echo View_Helper_Movimentacao::getClassRowMovimentacao($movimentacao->id_tipo_movimentacao); ?>">
            <td class="col-lg-1"><?php echo $movimentacao->tipo_movimentacao; ?></td>
            <td class="col-lg-4"><?php echo $movimentacao->descricao_movimentacao; ?></td>
            <td class="col-lg-3"><?php echo $movimentacao->descricao_categoria; ?></td>
            <td class="col-lg-1 text-right"><?php echo View_Helper_Currency::getCurrency($movimentacao->valor_movimentacao); ?></td>
            <td class="col-lg-1 text-center"><?php echo $movimentacao->realizado; ?></td>
            <td class="col-lg-2 text-center">
                Editar - Excluir
            </td>
        </tr>
        <?php endforeach; ?>
        <tr>
            <th colspan="3" class="text-right small">Total Receitas:</th>
            <th colspan="2"></th>            
        </tr>
        <tr>
            <th colspan="3">Total Despesas:</th>
            <th colspan="2"></th>            
        </tr>
        <tr>
            <th colspan="3">Saldo Dia:</th>
            <th colspan="2"></th>            
        </tr>
    </table>    
    <?php else : ?>
    <div class="text-warning">Nenhuma movimentação hoje.</div>
    <?php endif; ?>
</div>