<div class="row">    
    <div class="col-lg-12">    
        <?php echo View_Helper_Messages::render($this->messages); ?>       
        <div class="panel panel-info">
            <div class="panel-heading">
                Minhas Contas
                <div class="pull-right">
                    <a href="<?php echo $this->url(array(
                        'module' => 'cliente',
                        'controller' => 'contas',
                        'action' => 'nova-conta'
                    ), null, true); ?>">
                        <img src="<?php echo $this->baseUrl('views/img/icon_add.png'); ?>" width="25px" title="Cadastrar Conta"/>
                    </a>
                </div>
            </div>
            <div class="panel-body">
                <?php if ($this->contas->count() > 0) : ?>
                <table class="table table-striped table-responsive">
                    <tr>
                        <th>Banco</th>
                        <th>Descrição</th>
                        <th>Tipo</th>                        
                        <th class="text-right">Saldo Inicial</th>
                        <th class="text-center">Status</th>
                        <th class="text-center">Ações</th>
                    </tr>
                    <?php foreach ($this->contas as $conta) : ?>
                    <tr>
                        <td>
                            <?php if ($conta->logo_banco) : ?>
                            <img class="img img-thumbnail" src="<?php echo $this->baseUrl('views/img/bancos/' . $conta->logo_banco); ?>" />
                            <?php else : ?>
                            <img class="img img-thumbnail" src="<?php echo $this->baseUrl('views/img/bancos/icon_no.png'); ?>" />
                            <?php endif; ?>
                            <?php echo $conta->nome_banco ? $conta->nome_banco : 'Nenhum'; ?>
                        </td>
                        <td><?php echo $conta->descricao_conta; ?></td>
                        <td><?php echo $conta->descricao_tipo_conta; ?></td>                        
                        <td class="text-right"><?php echo View_Helper_Currency::getCurrency($conta->saldo_inicial); ?></td>                        
                        <td class="text-center"><?php echo $conta->ativo_conta ? 'Ativo' : 'Inativo'; ?></td>
                        <td class="text-center">
                            <a href="<?php echo $this->url(array(
                                'module' => 'cliente',
                                'controller' => 'contas',
                                'action' => 'editar-conta',
                                'id_conta' => $conta->id_conta
                            )); ?>">
                                <img class="margin-0px-5px" src="<?php echo $this->baseUrl('views/img/icon_edit.png'); ?>" width="20" title="Editar" />
                            </a>
                            <a href="<?php echo $this->url(array(
                                'module' => 'cliente',
                                'controller' => 'contas',
                                'action' => 'excluir-conta',
                                'id_conta' => $conta->id_conta
                            )); ?>">
                                <img class="margin-0px-5px" src="<?php echo $this->baseUrl('views/img/icon_delete.png'); ?>" width="20" title="Excluir" />
                            </a>
                        </td>
                    </tr>
                    <?php endforeach; ?>
                </table>
                <?php else : ?>
                <div class="text-warning">Nenhum registro</div>
                <?php endif; ?>
            </div>
        </div>
    </div>
</div>