<div class="row">
    <div class="col-lg-12">    
        <?php echo View_Helper_Messages::render($this->messages); ?>       
        <div class="panel panel-info">
            <div class="panel-heading">Pesquisa Avançada</div>
            <div class="panel-body">
                <p>
                    <i>Insira os filtros desejados</i>
                </p>
                <form class="form-inline">
                    <div class="form-group">
                        <?php echo $this->formPesquisa->palavra_chave; ?>
                    </div>
                    <div class="form-group">
                        <?php echo $this->formPesquisa->id_categoria; ?>
                    </div>
                    <div class="form-group">
                        <?php echo $this->formPesquisa->data_inicial; ?>
                    </div>
                    <div class="form-group">
                        <?php echo $this->formPesquisa->data_final; ?>
                    </div>
                    <div class="form-group">
                        <?php echo $this->formPesquisa->submit; ?>
                    </div>                    
              </form>
            </div>
        </div>
    </div>
</div>