<div class="row">
    <div class="col-lg-12">    
        <?php echo View_Helper_Messages::render($this->messages); ?>       
        <div class="panel panel-info">
            <div class="panel-heading">Pesquisa Avançada</div>
            <div class="panel-body">
                <p>
                    <i>Insira os filtros desejados</i>
                </p>
            </div>
        </div>
    </div>
</div>